tasks:
# NOTE: the before/init tasks here is just a dummy command
  - before: |
      dd if=/dev/zero of=/dev/null bs=512 count=1 conv=fsync || true
  - init: |
      dd if=/dev/zero of=/dev/null bs=512 count=1 conv=fsync || true
  - command: |
      yarn install && yarn build && yarn start
